/*
 * Node.js AI trainer entry point. Runs PPO self-play training and permanently
 * saves the trained network as js/ai/model/model.js (loaded by the browser
 * game's "trained" AI strategy), plus periodic checkpoints under
 * train/checkpoints/.
 *
 * Usage:
 *   node train/train.js [--iterations 200] [--rollout-size 2048]
 *                        [--start-number 1000] [--max-steps 100]
 *                        [--eval-every 10] [--checkpoint-every 20]
 *                        [--games-per-baseline 20] [--resume path/to/checkpoint.json]
 *
 * No external dependencies - pure Node.js + the hand-written network in
 * js/ai/neuralnet.js.
 */
const fs = require('fs');
const path = require('path');
const nn = require(path.join(__dirname, '..', 'js', 'ai', 'neuralnet.js'));
const features = require(path.join(__dirname, '..', 'js', 'ai', 'features.js'));
const { collectRollout, ppoUpdate } = require('./ppo');
const { evaluateAgainstBaselines } = require('./evaluator');

function parseArgs(argv) {
    const args = {
        iterations: 200,
        rolloutSize: 2048,
        startNumber: 1000n,
        maxSteps: 100,
        evalEvery: 10,
        checkpointEvery: 20,
        gamesPerBaseline: 20,
        resume: null
    };
    for (let i = 0; i < argv.length; i++) {
        const key = argv[i];
        const value = argv[i + 1];
        switch (key) {
            case '--iterations': args.iterations = parseInt(value, 10); i++; break;
            case '--rollout-size': args.rolloutSize = parseInt(value, 10); i++; break;
            case '--start-number': args.startNumber = BigInt(value); i++; break;
            case '--max-steps': args.maxSteps = parseInt(value, 10); i++; break;
            case '--eval-every': args.evalEvery = parseInt(value, 10); i++; break;
            case '--checkpoint-every': args.checkpointEvery = parseInt(value, 10); i++; break;
            case '--games-per-baseline': args.gamesPerBaseline = parseInt(value, 10); i++; break;
            case '--resume': args.resume = value; i++; break;
            default: break;
        }
    }
    return args;
}

function ensureDir(dirPath) {
    if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath, { recursive: true });
}

function checkpointTimestamp(date) {
    return date.toISOString().replace(/[-:.]/g, '');
}

function saveCheckpoint(net, optState, iteration, checkpointsDir) {
    const filePath = path.join(checkpointsDir, `checkpoint-${checkpointTimestamp(new Date())}-iter-${iteration}.json`);
    fs.writeFileSync(filePath, JSON.stringify({ net: nn.networkToJSON(net), optState, iteration }));
    return filePath;
}

function saveBrowserModel(net, metadata, modelPath) {
    const payload = {
        version: 1,
        featureSize: features.FEATURE_SIZE,
        actionSlots: features.ACTION_SLOTS,
        trainedAt: new Date().toISOString(),
        metadata,
        network: nn.networkToJSON(net)
    };
    const content = `/*\n * Trained neural network, auto-generated by \`node train/train.js\`.\n * Do not edit by hand - retrain to update.\n */\nlet TRAINED_MODEL_DATA = ${JSON.stringify(payload)};\n`;
    fs.writeFileSync(modelPath, content);
}

function main() {
    const args = parseArgs(process.argv.slice(2));
    const checkpointsDir = path.join(__dirname, 'checkpoints');
    const modelPath = path.join(__dirname, '..', 'js', 'ai', 'model', 'model.js');
    ensureDir(checkpointsDir);

    let net;
    let optState;
    if (args.resume) {
        const data = JSON.parse(fs.readFileSync(args.resume, 'utf8'));
        net = nn.networkFromJSON(data.net);
        optState = data.optState;
        console.log(`Resumed from ${args.resume} (iteration ${data.iteration})`);
    } else {
        net = nn.createNetwork(features.FEATURE_SIZE, features.ACTION_SLOTS);
        optState = nn.createOptimizerState(net);
    }

    const ppoConfig = {
        gamma: 0.99,
        lambda: 0.95,
        clipRange: 0.2,
        entropyCoef: 0.01,
        valueCoef: 0.5,
        learningRate: 3e-4,
        epochs: 4,
        batchSize: 64,
        rolloutSize: args.rolloutSize,
        startNumber: args.startNumber,
        maxSteps: args.maxSteps,
        randomStart: true,
        startRange: 1_000_000
    };

    let bestScore = -Infinity;

    console.log(`Starting PPO training: ${args.iterations} iterations, rollout size ${args.rolloutSize}, feature size ${features.FEATURE_SIZE}`);

    for (let iteration = 1; iteration <= args.iterations; iteration++) {
        const startTime = Date.now();
        const { samples, episodeStats } = collectRollout(net, ppoConfig);
        const avgLoss = ppoUpdate(net, optState, samples, ppoConfig);

        const wins = episodeStats.filter(e => e.winner !== null).length;
        const ties = episodeStats.filter(e => e.winner === null).length;
        const elapsedMs = Date.now() - startTime;
        console.log(`[iter ${iteration}/${args.iterations}] episodes=${episodeStats.length} samples=${samples.length} decisive=${wins} ties=${ties} avgLoss=${avgLoss.toFixed(4)} time=${elapsedMs}ms`);

        if (iteration % args.evalEvery === 0 || iteration === args.iterations) {
            const evalResult = evaluateAgainstBaselines(net, {
                startNumber: args.startNumber,
                maxSteps: args.maxSteps,
                gamesPerBaseline: args.gamesPerBaseline
            });
            console.log(`  eval avgScore=${evalResult.averageScore.toFixed(3)}`, JSON.stringify(evalResult.perBaseline));

            if (evalResult.averageScore > bestScore) {
                bestScore = evalResult.averageScore;
                saveBrowserModel(net, { iteration, averageScore: bestScore, perBaseline: evalResult.perBaseline }, modelPath);
                console.log(`  New best model saved to ${modelPath} (avgScore=${bestScore.toFixed(3)})`);
            }
        }

        if (iteration % args.checkpointEvery === 0 || iteration === args.iterations) {
            const savedPath = saveCheckpoint(net, optState, iteration, checkpointsDir);
            console.log(`  Checkpoint saved: ${savedPath}`);
        }
    }

    console.log('Training complete.');
}

main();
